apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-controller-manager-operator
  name: openshift-controller-manager-operator
  labels:
    app: openshift-controller-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-controller-manager-operator
  template:
    metadata:
      name: openshift-controller-manager-operator
      labels:
        app: openshift-controller-manager-operator
    spec:
      serviceAccountName: openshift-controller-manager-operator
      containers:
      - name: operator
        image: docker.io/openshift/origin-cluster-openshift-controller-manager-operator:v4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        command: ["cluster-openshift-controller-manager-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        - "-v=4"
        resources:
          requests:
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        env:
        - name: IMAGE
          value: quay.io/openshift/origin-hypershift:v4.0
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 400
          secretName: openshift-controller-manager-operator-serving-cert
          optional: true
      - name: config
        configMap:
          defaultMode: 440
          name: openshift-controller-manager-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
