apiVersion: operator.openshift.io/v1
kind: OpenShiftControllerManager
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
  imagePullSpec: openshift/origin-hypershift:latest
  version: 3.11.0
  logging:
    level: 4
  replicas: 2
