apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-controller-manager-operator
  name: openshift-controller-manager-operator-config
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: GenericOperatorConfig
