apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-controller-manager:service-ingress-ip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:openshift-controller-manager:service-ingress-ip-controller
subjects:
- kind: ServiceAccount
  name: service-ingress-ip-controller
  namespace: openshift-infra
